# Generated by Django 3.0.6 on 2020-05-24 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=50)),
                ('year_offered', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('enrollment_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('batch', models.CharField(max_length=10, null=True)),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollment_app.Subject')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('subject_id', 'username')},
            },
        ),
    ]
