# Generated by Django 3.0.6 on 2020-05-24 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('challenge_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('testcase_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('input', models.FileField(upload_to='')),
                ('output', models.FileField(upload_to='')),
                ('marks', models.PositiveIntegerField(default=0)),
                ('is_hidden', models.BooleanField(default=False)),
                ('execution_time_limit', models.PositiveIntegerField(default=2000)),
                ('challenge_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge_app.Challenge')),
            ],
            options={
                'unique_together': {('challenge_id', 'title')},
            },
        ),
        migrations.CreateModel(
            name='ChallengeOwner',
            fields=[
                ('challenge_owner_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('challenge_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge_app.Challenge')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('challenge_id', 'owner')},
            },
        ),
    ]
