# Generated by Django 3.0.6 on 2020-05-24 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lab_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenge_app', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('submission_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('submission_datetime', models.DateTimeField(auto_now_add=True)),
                ('solution_file', models.FileField(upload_to='')),
                ('testcase_results', models.CharField(max_length=1000)),
                ('marks', models.PositiveIntegerField(default=0)),
                ('challenge_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge_app.Challenge')),
                ('lab_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_app.Lab')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
